# Global configuration settings for Prometheus
global:
  # Set the interval at which Prometheus scrapes targets (15 seconds)
  scrape_interval: 5s
# Scrape configurations for Prometheus, defining jobs and their settings
scrape_configs:
  # Job configuration for 'fastapi'
  - job_name: 'api'
    # Define static targets for this job
    static_configs:
      - targets: ['api:8000']